import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from typing import List, Optional


def send_email_smtp(
    to_email: str,
    subject: str,
    body: str,
    sender_email: str,
    app_password: str,
    attachment_paths: Optional[List[str]] = None,
) -> str:
    """Send an email through the sender's own Gmail mailbox via SMTP + an
    App Password (not the Gmail API OAuth send scope). This makes the
    email land in the sender's real Sent folder and inherit their
    mailbox's sending reputation, instead of going out through a shared
    SES sender identity.

    Args:
        to_email: Recipient email address.
        subject: Email subject line.
        body: Plain-text email body.
        sender_email: The user's own Gmail address (the "From" and the
            SMTP login username).
        app_password: A 16-character Gmail App Password generated by the
            user (requires 2-Step Verification enabled on their Google
            account). This is NOT their regular Gmail password.
        attachment_paths: Optional list of local image file paths to
            attach (screenshots, demo proof, etc).
    """
    msg = MIMEMultipart()
    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = to_email
    msg.attach(MIMEText(body, "plain"))

    for path in attachment_paths or []:
        if not path or not os.path.exists(path):
            continue
        with open(path, "rb") as f:
            img = MIMEImage(f.read())
            img.add_header(
                "Content-Disposition", "attachment", filename=os.path.basename(path)
            )
            msg.attach(img)

    # smtp.gmail.com:465 is Gmail's SMTP-over-SSL endpoint. App Passwords
    # work here without needing OAuth or Google's sensitive-scope review.
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender_email, app_password)
        smtp.sendmail(sender_email, [to_email], msg.as_string())

    return f"Email sent to {to_email} via {sender_email}'s mailbox"


def verify_mailbox_credentials(sender_email: str, app_password: str) -> None:
    """Raises an exception if the given Gmail address + App Password
    can't authenticate. Used right after a user pastes their App Password
    into settings, so we fail fast with a clear error instead of only
    finding out the credentials are bad when a real send is attempted."""
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender_email, app_password)